MTEngine:
    MTengine: Moses
    startMTEngine: True
    startCommand: "./moses -f moses.ini --server --server-port 8080 --print-alignment-info&"
    IP: localhost
    port: 8080
    #The port is needed for MTUOC-stop-server.py
    
MTUOCServer:
  port: 8000
  type: MTUOC
  #one of MTUOC, Moses, ModernMT, OpenNMT, NMTWizard
  verbose: True
  restore_tags: True
  restore_case: True
  URLs: True
  EMAILs: True
  
  ONMT_url_root: "/translator"
  #specific configuration when acting as ONMT server

Preprocess:
  sl_lang: en
  tl_lang: es
  sl_tokenizer: MTUOC_tokenizer_eng.py
  tl_tokenizer: MTUOC_tokenizer_spa.py
  sp_vocabulary_SL: vocab_file.en
  tcmodel: tc.en
  

