MTUOC: /MTUOC4.0

trainPreCorpus: train-pre-eng-spa.txt
valPreCorpus: val-pre-eng-spa.txt

SL: en
TL: es

#VERBOSE
VERBOSE: True

#SUBWORDS
LEARN_BPE: True
joiner: "@@"
#use one of ￭ or @@
SPLIT_NUMBERS: True
bos: <s>
bos_annotate: True
eos: </s>
eos_annotate: True
NUM_OPERATIONS: 85000
JOIN_LANGUAGES: False
APPLY_BPE: True
VOCABULARY_THRESHOLD: 50
BPE_DROPOUT: True
BPE_DROPOUT_P: 0.1

#GUIDED ALIGNMENT
#TRAIN CORPUS
GUIDED_ALIGNMENT: True
ALIGNER: eflomal
#one of eflomal, fast_align
DELETE_EXISTING: True
SPLIT_LIMIT: 1000000
#For efomal, max number of segments to align at a time

#VALID CORPUS
GUIDED_ALIGNMENT_VALID: True
ALIGNER_VALID: eflomal
#one of eflomal, fast_align
DELETE_EXISTING_VALID: True

DELETE_TEMP: True
