# Marian configuration file generated at 2020-08-06 07:16:22 +0000 with version v1.9.32; d8bddcfa 2020-08-03 19:47:45 +0100
# General options
authors: false
cite: false

model: model.npz
pretrained-model: ""

train-sets:
  - train.sp.en
  - train.sp.es
vocabs:
  - vocab-en.yml
  - vocab-es.yml
dim-vocabs:
  - 100000
  - 100000

valid-sets:
  - val.sp.en
  - val.sp.es

guided-alignment: train.sp.es.en.align

keep-best: true
overwrite: true

early-stopping: 5

devices:
  - 0
  
workspace: 5000


build-info: ""
log: train.log
log-level: info
log-time-zone: ""
quiet: false
quiet-translation: true
seed: 1111
clip-gemm: 0
interpolate-env-vars: false
relative-paths: false
# Model options

ignore-model-config: false
type: s2s

dim-emb: 512
lemma-dim-emb: 0
dim-rnn: 1024
enc-type: bidirectional
enc-cell: gru
enc-cell-depth: 1
enc-depth: 1
dec-cell: gru
dec-cell-base-depth: 2
dec-cell-high-depth: 1
dec-depth: 1
skip: false
layer-normalization: true
right-left: false
input-types:
  []
best-deep: false
tied-embeddings: false
tied-embeddings-src: false
tied-embeddings-all: false
transformer-heads: 8
transformer-no-projection: false
transformer-dim-ffn: 2048
transformer-ffn-depth: 2
transformer-ffn-activation: swish
transformer-dim-aan: 2048
transformer-aan-depth: 2
transformer-aan-activation: swish
transformer-aan-nogate: false
transformer-decoder-autoreg: self-attention
transformer-tied-layers:
  []
transformer-guided-alignment-layer: last
transformer-preprocess: ""
transformer-postprocess-emb: d
transformer-postprocess: dan
transformer-train-position-embeddings: false
transformer-depth-scaling: false
bert-mask-symbol: "[MASK]"
bert-sep-symbol: "[SEP]"
bert-class-symbol: "[CLS]"
bert-masking-fraction: 0.15
bert-train-type-embeddings: true
bert-type-vocab-size: 2
dropout-rnn: 0.2
dropout-src: 0.1
dropout-trg: 0.1
grad-dropping-rate: 0
grad-dropping-momentum: 0
grad-dropping-warmup: 100
transformer-dropout: 0
transformer-dropout-attention: 0
transformer-dropout-ffn: 0
# Training options
cost-type: ce-mean
multi-loss-type: sum
unlikelihood-loss: false
no-reload: false

after-epochs: 0
after-batches: 0
disp-freq: 1000
disp-first: 0
disp-label-counts: false
save-freq: 10000
max-length: 50
max-length-crop: false
tsv: false
tsv-fields: 0
shuffle: data
no-shuffle: false
no-restore-corpus: false
tempdir: /tmp
sqlite: ""
sqlite-drop: false
num-devices: 0
no-nccl: false
cpu-threads: 0
mini-batch: 64
mini-batch-words: 0
mini-batch-fit: true
mini-batch-fit-step: 10
gradient-checkpointing: false
maxi-batch: 100
maxi-batch-sort: trg
shuffle-in-ram: false
all-caps-every: 0
english-title-case-every: 0
mini-batch-words-ref: 0
mini-batch-warmup: 0
mini-batch-track-lr: false
optimizer: adam
optimizer-params:
  []
optimizer-delay: 1
sync-sgd: false
learn-rate: 0.0001
lr-report: false
lr-decay: 0
lr-decay-strategy: epoch+stalled
lr-decay-start:
  - 10
  - 1
lr-decay-freq: 50000
lr-decay-reset-optimizer: false
lr-decay-repeat-warmup: false
lr-decay-inv-sqrt:
  - 0
lr-warmup: 0
lr-warmup-start-rate: 0
lr-warmup-cycle: false
lr-warmup-at-reload: false
label-smoothing: 0
factor-weight: 1
clip-norm: 1
exponential-smoothing: 0.0001
guided-alignment-cost: mse
guided-alignment-weight: 0.1
data-weighting: ""
data-weighting-type: sentence
embedding-vectors:
  []
embedding-normalization: false
embedding-fix-src: false
embedding-fix-trg: false
fp16: false
precision:
  - float32
  - float32
  - float32
cost-scaling:
  []
normalize-gradient: false
multi-node: false
multi-node-overlap: true
ulr: false
ulr-query-vectors: ""
ulr-keys-vectors: ""
ulr-trainable-transformation: false
ulr-dim-emb: 0
ulr-dropout: 0
ulr-softmax-temperature: 1
task:
  []
# Validation set options

valid-freq: 10000
valid-metrics:
  - bleu
valid-reset-stalled: false
beam-size: 12
normalize: 1
max-length-factor: 3
word-penalty: 0
allow-unk: false
n-best: false
word-scores: false
valid-mini-batch: 32
valid-max-length: 1000
valid-script-path: ""
valid-script-args:
  []
valid-translation-output: ""
valid-log: valid.log
