MTUOC: /MTUOC4.0

#input corpora
corpus_SPE: corpusSPE-eng-spa.txt
corpus_GEN: corpusGEN-eng-spa.txt

#output corpora
corpusTRAIN: train-eng-spa.txt
corpusVAL: val-eng-spa.txt
corpusEVAL: eval-eng-spa.txt

#sizes
GEN_selected_segments: 10000
lval: 1000
leval: 1000

#languages and tokenizers
SL: en
TL: es
SL_tokenizer: MTUOC_tokenizer_eng


