MTUOC: /MTUOC4.0

trainPreCorpus: train-pre-eng-spa.txt
valPreCorpus: val-pre-eng-spa.txt

SL: en
TL: es

#VERBOSE
VERBOSE: True

#SENTENCE PIECE
SP_MODEL_PREFIX: spmodel
MODEL_TYPE: bpe
#one of unigram, bpe, char, word
JOIN_LANGUAGES: True
VOCAB_SIZE: 64000
CHARACTER_COVERAGE: 1.0
CHARACTER_COVERAGE_SL: 1.0
CHARACTER_COVERAGE_TL: 1.0
VOCABULARY_THRESHOLD: 50
INPUT_SENTENCE_SIZE: 5000000
bos: <s>
eos: </s>

#GUIDED ALIGNMENT
#TRAIN CORPUS
GUIDED_ALIGNMENT: True
ALIGNER: eflomal
#one of eflomal, fast_align
DELETE_EXISTING: True
SPLIT_LIMIT: 1000000
#For efomal, max number of segments to align at a time

#VALID CORPUS
GUIDED_ALIGNMENT_VALID: True
ALIGNER_VALID: eflomal
#one of eflomal, fast_align
DELETE_EXISTING_VALID: True

DELETE_TEMP: True
