MTUOC: /MTUOC

ROOTNAME: corpus

SL: en
TL: es

#VERBOSE
VERBOSE: True

#TOKENIZATION
TOKENIZE_SL: True
SL_TOKENIZER: MTUOC_tokenizer_eng
TOKENIZE_TL: True
TL_TOKENIZER: MTUOC_tokenizer_spa

#CLEANING
CLEAN: True
CLEAN_MIN_TOK: 1
CLEAN_MAX_TOK: 80

#SENTENCE PIECE
MODEL_TYPE: bpe
#one of unigram, bpe, char, word
JOIN_LANGUAGES: True
VOCAB_SIZE: 64000
CHARACTER_COVERAGE: 1.0
CHARACTER_COVERAGE_SL: 1.0
CHARACTER_COVERAGE_TL: 1.0
INPUT_SENTENCE_SIZE: 1000000

#SPLITTING CORPUS
SPLIT_CORPUS: True
lval: 1000
leval: 1000

#GUIDED ALIGNMENT
#TRAIN CORPUS
GUIDED_ALIGNMENT: True
ALIGNER: eflomal
#one of eflomal, fast_align
BOTH_DIRECTIONS: True 
#only for fast_align, eflomal aligns always the two directions at the same time
DELETE_EXISTING: True
DELETE_TEMP: True
SPLIT_LIMIT: 10000
#For efomal, max number of segments to align at a time

#VALID CORPUS
GUIDED_ALIGNMENT_VALID: True
ALIGNER_VALID: eflomal
#one of eflomal, fast_align
BOTH_DIRECTIONS_VALID: True 
#only for fast_align, eflomal aligns always the two directions at the same time
DELETE_EXISTING_VALID: True
DELETE_TEMP_VALID: True
