ROOTNAME: corpus
SL: en
TL: es

#MTUOC's scripts directory
MTUOC: /MTUOC

#TOKENIZATION
TOKENIZE_SL: True
SLTOKENIZER: MTUOC_tokenizer_eng
TOKENIZE_TL: True
TLTOKENIZER: MTUOC_tokenizer_spa
    
#CLEANING
CLEAN: True
CLEAN_MIN_TOK: 1
CLEAN_MAX_TOK: 80

#TRUECASING
LEARN_TRUECASER_SL: True
SLDICT: /MTUOC3/eng.dict
LEARN_TRUECASER_TL: True
TLDICT: /MTUOC3/spa.dict
TRUECASE_SL: True
TRUECASE_TL: True

#SPLITTING CORPUS
SPLIT_CORPUS: True
lval: 1000
leval: 1000

#SUBWORDS
LEARN_BPE: True
joiner: ￭
#use one of ￭ or @@
bos: <s>
bos_annotate: True
eos: </s>
eos_annotate: True
NUM_OPERATIONS: 85000
JOIN_LANGUAGES: True
APPLY_BPE: True
VOCABULARY_THRESHOLD: 50
BPE_DROPOUT: True
BPE_DROPOUT_P: 0.1

#GUIDED ALIGNMENT
#TRAIN CORPUS
GUIDED_ALIGNMENT: True
ALIGNER: eflomal
#one of eflomal, fast_align
BOTH_DIRECTIONS: True 
#only for fast_align, eflomal aligns always the two directions at the same time
DELETE_EXISTING: True
DELETE_TEMP: True

#GUIDED ALIGNMENT
#VALID CORPUS
GUIDED_ALIGNMENT_VALID: True
ALIGNER_VALID: eflomal
#one of eflomal, fast_align
BOTH_DIRECTIONS_VALID: True 
#only for fast_align, eflomal aligns always the two directions at the same time
DELETE_EXISTING_VALID: True
DELETE_TEMP_VALID: True
